fix graphviz install on macos-13

diff --git a/.github/workflows/python_ci.yml b/.github/workflows/python_ci.yml
--- a/.github/workflows/python_ci.yml
+++ b/.github/workflows/python_ci.yml
@@ -45,9 +45,15 @@ jobs:
           choco install -y graphviz
           New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
           git config --system core.longpaths true
-    
+
+      - name: Install Dependencies (macos-13)
+        if: matrix.os == 'macos-13'
+        run: |
+          # || true is needed to avoid failure on brew link error with python3.12
+          brew install graphviz || true
+
       - name: Install Dependencies (macos)
-        if: matrix.os == 'macos-13' || matrix.os == 'macos-latest'
+        if: matrix.os == 'macos-latest'
         run: |
           brew install graphviz
 
